---

# Set failed
- set_fact:
    cacheable: true
    sas_logon_policy_for_ad_user:
      unreachable: false
      failed: true
      changed: false
  when: logon_policy_for_ad_user_reports_generate or logon_policy_for_ad_user_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
