---

# ------------------------------------------------------------------------------
# AIX - remove package
# ------------------------------------------------------------------------------

# Cleanup any failed installation before removal
- name: cleanup before removal of {{ package }}
  command:
    cmd: installp -C {{ package }}
  register: pkg_remove

# Remove package
- name: remove {{ package }}
  command:
    cmd: installp -u {{ package }}
  register: pkg_remove
