---

# Report parameters
# ------------------------------------------------------------------------------

unix_computers_in_ad_base_container: ''

# Reports settings
# ------------------------------------------------------------------------------

unix_computers_in_ad_reports_generate: "{{ reports_generate }}"
unix_computers_in_ad_reports_backup: "{{ reports_backup }}"

# On which host should the reports be generated.
# TODO: This has only been tested on the Ansible control node (127.0.0.1)
unix_computers_in_ad_reports_host: "{{ reports_host }}"

# List of reports to generate
# src:  Is the report template file on the Ansible control node.
#       With no or relative path Ansible will look in the unix_computers_in_ad role template directory.
#       Full path to find the template files elsewhere on the Ansible control node.
# dest: Is the destination file on the host (unix_computers_in_ad_reports_host.)
#       With no or relative path when the destination is the Ansible control node.
#       (unix_computers_in_ad_reports_host = 127.0.0.1) relative to the playbook directory.
#       Full path for other locations or on other hosts.
#       In either case the directory must already exist.
unix_computers_in_ad_reports: 
  - src:  unix_computers_in_ad_report.csv.j2
    dest: unix_computers_in_ad_report.csv
  - src:  unix_computers_in_ad_report.html.j2
    dest: unix_computers_in_ad_report.html
