---

# ------------------------------------------------------------------------------
# Debian - remove package 
# ------------------------------------------------------------------------------

# Remove package
- name: remove {{ package }}
  command:
    cmd: dpkg --purge {{ package }}
  register: pkg_remove 
