---

# Set failed
- set_fact:
    cacheable: true
    sas_client_join:
      unreachable: false 
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        client_join:
        {{ result.msg | default('Unexpected error') }}
    sas_client: 
      unreachable: false 
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        client_join:
        {{ result.msg | default('Unexpected error') }}
  when: client_join_reports_generate or client_join_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
