---

# ------------------------------------------------------------------------------
# HP-UX - grab package version 
# ------------------------------------------------------------------------------

# Grab installed version of package 
- name: get {{ package }} version
  shell:
    cmd: swlist | grep {{ package }}
  register: pkg_version
  changed_when: false
  failed_when: false
  ignore_errors: true
