---

# Set success
- set_fact:
    cacheable: true
    sas_local_unix_user_conflicts:
      unreachable: false
      failed: false
      changed: false
  when: local_unix_user_conflicts_reports_generate or local_unix_user_conflicts_facts_generate
