---

# Set success
- set_fact:
    cacheable: true
    sas_unix_enabled_ad_users:
      unreachable: false
      failed: false
      changed: false
      result: "{{ users_result }}"
  when: unix_enabled_ad_users_reports_generate
