---

# Set unreachable
- set_fact:
    cacheable: true
    sas_unix_enabled_ad_users:
      unreachable: true
      failed: true
      changed: false
  when: unix_enabled_ad_users_reports_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
