---

# Set success
- set_fact:
    cacheable: true
    sas_host_access_control:
      unreachable: false
      failed: false
      changed: false
  when: host_access_control_reports_generate or host_access_control_facts_generate
