---

# Facts settings
# ------------------------------------------------------------------------------

logon_policy_for_unix_host_facts_generate: "{{ facts_generate }}"


# Reports settings
# ------------------------------------------------------------------------------

logon_policy_for_unix_host_reports_generate: "{{ reports_generate }}"
logon_policy_for_unix_host_reports_backup: "{{ reports_backup }}"

# On which host should the reports be generated.
# TODO: This has only been tested on the Ansible control node (127.0.0.1)
logon_policy_for_unix_host_reports_host: "{{ reports_host }}"

# List of reports to generate
# src:  Is the report template file on the Ansible control node.
#       With no or relative path Ansible will look in the logon_policy_for_unix_host role template directory.
#       Full path to find the template files elsewhere on the Ansible control node.
# dest: Is the destination file on the host (logon_policy_for_unix_host_reports_host.)
#       With no or relative path when the destination is the Ansible control node.
#       (logon_policy_for_unix_host_reports_host = 127.0.0.1) relative to the playbook directory.
#       Full path for other locations or on other hosts.
#       In either case the directory must already exist.
logon_policy_for_unix_host_reports:
  - src:  logon_policy_for_unix_host_report.csv.j2
    dest: logon_policy_for_unix_host_report.csv
  - src:  logon_policy_for_unix_host_report.html.j2
    dest: logon_policy_for_unix_host_report.html
