---

# ------------------------------------------------------------------------------
# Darwin - grab package version 
# ------------------------------------------------------------------------------

# Grab installed version of vasclnt(s) and vasgp(s) packages
- name: get {{ package }} version
  command:
    cmd: pkgutil --regexp --pkg-info .*{{ package }}
  register: pkg_version 
  changed_when: false
  failed_when: false
  ignore_errors: true
