---

# Set failed
- name: set failed
  set_fact:
    cacheable: true
    sas_client_config:
      unreachable: false
      failed: true
      changed: "{{ sas_client_config_changed | default(false) }}"
      msg: |
        client_config:
        {{ result.msg | default('Unexpected error') }}
    sas_client:
      unreachable: false
      failed: true
      changed: "{{ sas_client_config_changed | default(false) }}"
      msg: |
        client_config:
        {{ result.msg | default('Unexpected error') }}
  when: client_config_reports_generate or client_config_facts_generate

# Propogate fail
- name: fail
  fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
