---

# Set details
- set_fact:
    sas_client_config_{{ file }}:
        changed: "{{ changed }}"
        failed: "{{ failed }}"
        msg: "{{ msg }}" 
        results: "{{ results }}"
    cacheable: true
