---

# Set success
- set_fact:
    cacheable: true
    sas_client_config:  
      unreachable: false
      failed: false
      changed: "{{ result.changed | default(False) }}"
      msg: ''
    sas_client: 
      unreachable: false 
      failed: false
      changed: "{{ result.changed | default(False) }}"
      msg: ''
  when: client_config_reports_generate or client_config_facts_generate
