---

# Set success
- name: set success
  set_fact:
    cacheable: true
    sas_client_config:
      unreachable: false
      failed: false
      changed: "{{ sas_client_config_changed | default(false) }}"
      msg: ''
    sas_client:
      unreachable: false
      failed: false
      changed: "{{ sas_client_config_changed | default(false) }}"
      msg: ''
  when: client_config_reports_generate or client_config_facts_generate
