---

- hosts: all
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Active Directory
    client_domain: sample.net
    client_username: user
    client_password: pass

    # Report parameters
    ad_user_conflicts_base_container: 'CN=Users,DC=Sample,DC=net'

    # Reports
    ad_user_conflicts_reports_generate: true
    ad_user_conflicts_reports_backup: false

  roles:
    - name: oneidentity.authentication_services.ad_user_conflicts

