---

- name: generate reports
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: "{{ logon_policy_for_ad_user_reports_backup }}"
  with_items: "{{ logon_policy_for_ad_user_reports }}"
  delegate_to: "{{ logon_policy_for_ad_user_reports_host }}"
  run_once: true
  changed_when: false
  vars:
    ansible_become: false
