---

# Set unreachable
- set_fact:
    cacheable: true
    sas_ad_group_conflicts:
      unreachable: true
      failed: true
      changed: false
  when: ad_group_conflicts_reports_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
