---

# Set failed
- set_fact:
    cacheable: true
    sas_client_preflight:
      unreachable: false 
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        client_preflight:
        {{ result.msg | default('Unexpected error') }}
    sas_client: 
      unreachable: false 
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        client_preflight:
        {{ result.msg | default('Unexpected error') }} 
  when: client_preflight_reports_generate or client_preflight_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
