---

# Set unreachable
- set_fact:
    cacheable: true
    sas_client_agent_status:
      unreachable: true
      failed: true
      changed: false
      msg: |
        client_agent_status:
        {{ result.msg | default('Unexpected error') }}
    sas_client:
      unreachable: true
      failed: true
      changed: false
      msg: |
        client_agent_status:
        {{ result.msg | default('Unexpected error') }}
  when: client_agent_status_reports_generate or client_agent_status_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
