---

# Set success
- set_fact:
    cacheable: true
    sas_client_agent_status:
      unreachable: false
      failed: false
      changed: false
      msg: ''
    sas_client:
      unreachable: false
      failed: false
      changed: false
      msg: ''
  when: client_agent_status_reports_generate or client_agent_status_facts_generate
