---

# Client software state
# ------------------------------------------------------------------------------

# State values:
# - check: check only, no changes to system
# - present: ensure installed and the same version as in client_sw_dir
# - absent: ensure not intalled 
client_sw_pkg_state:
  vasclnt: check 
  vasclnts: check 
  vasgp: check 
  vasgps: check 
  vassc: check 
  vascert: check 
  dnsupdate: check 
  pamdefender: check 
  vasyp: check 
  vasqa: check 
  vasproxy: check 
  vasdev: check 


# Facts settings
# ------------------------------------------------------------------------------

client_sw_facts_generate: "{{ facts_generate }}"
client_sw_facts_verbose: "{{ facts_verbose }}"


# Reports settings
# ------------------------------------------------------------------------------

client_sw_reports_generate: "{{ reports_generate }}"
client_sw_reports_backup: "{{ reports_backup }}"

# Format of details section in both HTML and CSV reports
# Valid options are: 'yaml' or 'json'
client_sw_reports_details_format: "{{ reports_details_format }}"

# On which host should the reports be generated.
# TODO: This has only been tested on the Ansible control node (127.0.0.1)
client_sw_reports_host: "{{ reports_host }}"

# List of reports to generate
# src:  Is the report template file on the Ansible control node.
#       With no or relative path Ansible will look in the client_sw role template directory.  
#       Full path to find the template files elsewhere on the Ansible control node. 
# dest: Is the destination file on the host (client_sw_reports_host.) 
#       With no or relative path when the destination is the Ansible control node.
#       (client_sw_reports_host = 127.0.0.1) relative to the playbook directory.
#       Full path for other locations or on other hosts.  
#       In either case the directory must already exist.
client_sw_reports: 
  - src:  client_sw_report.csv.j2   
    dest: client_sw_report.csv
  - src:  client_sw_report.html.j2
    dest: client_sw_report.html
