---

# Set failed
- set_fact:
    cacheable: true
    sas_logon_policy_for_unix_host:
      unreachable: false
      failed: true
      changed: false
  when: logon_policy_for_unix_host_reports_generate or logon_policy_for_unix_host_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
