---

# Set success
- set_fact:
    cacheable: true
    sas_local_unix_users_with_ad_logon:
      unreachable: false
      failed: false
      changed: false
  when: local_unix_users_with_ad_logon_reports_generate or local_unix_users_with_ad_logon_facts_generate
