---

# Users allow
- include_tasks: config_files/simple_file.yml
  vars:
    file_name: users_allow
    file_path: "{{ client_config_users_allow_path }}"
    file_create: "{{ client_config_users_allow_create }}"
    file_mode: "{{ client_config_users_allow_mode }}"
    file_owner: "{{ client_config_users_allow_owner }}"
    file_group: "{{ client_config_users_allow_group }}"
    file_backup: "{{ client_config_users_allow_backup }}"
    file_values: "{{ client_config_users_allow }}"
