---

# Set success
- set_fact:
    cacheable: true
    sas_client_sw:  
      unreachable: false
      failed: false
      changed: false
      msg: ''
    sas_client: 
      unreachable: false 
      failed: false
      changed: false
      msg: '' 
  when: client_sw_reports_generate or client_sw_facts_generate
