---

# Create temporary directory on host
- name: create temp directory {{ package_dest_dir }} 
  file:
    path: "{{ package_dest_dir }}"
    state: directory 
  ignore_errors: True
  changed_when: false
